language: c
sudo: required

cache:
  directories:
  - $HOME/.opam

env:
  global:
  - OPAMJOBS="2"
  - OPAMYES="true"
  matrix:
  - OCAML_VERSION=4.04
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07
  - OCAML_VERSION=4.08
  - OCAML_VERSION=4.09

os:
  - linux

before_install:
  # Obtain and install opam locally.
  - sudo wget https://github.com/ocaml/opam/releases/download/2.0.0/opam-2.0.0-x86_64-linux -O /usr/bin/opam
  - sudo chmod 755 /usr/bin/opam
  # Initialize the switch.
  - opam init -a --disable-sandboxing --compiler="$OCAML_VERSION"
  - opam update
  - opam switch "$OCAML_VERSION"
  - eval $(opam env)
  - opam install dune>=1.9.0 sqlite3
  - git clone https://github.com/craff/pacomb.git
  - opam pin add -k path pacomb.1.0 pacomb

install:
  - dune build
  - dune install

script:
  - dune runtest
